# Generated by Django 6.0.3 on 2026-03-17 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('ANIME', 'Anime'), ('MANGA', 'Manga')], max_length=16)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('WATCHING', 'Watching/Reading'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('DROPPED', 'Dropped')], max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_library_user_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'external_id'), name='uniq_libraryentry_user_external_id')],
            },
        ),
    ]
