# Generated by Django 6.0.3 on 2026-06-28 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_catalogitem_libraryentry_catalog_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='libraryentry',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_library_user_favorite'),
        ),
    ]
