# Generated by Django 6.0.3 on 2026-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='average_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='chapters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='format',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='release_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='season_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='site_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='volumes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
