# Generated by Django 6.0.3 on 2026-09-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_mediacomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('WATCHING', 'Watching/Reading'), ('COMPLETED', 'Completed'), ('REWATCHING', 'Rewatching/Rereading'), ('ON_HOLD', 'Paused'), ('DROPPED', 'Dropped')], max_length=16),
        ),
    ]
