# Generated by Django 6.0.3 on 2026-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_libraryentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
