# Generated by Django 6.0.3 on 2026-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_catalogitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_has_transparency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, upload_to='profile_banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
    ]
